In [1]:
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
fishData=np.genfromtxt('fish_data.csv',delimiter=',', skip_header=1) 

In [5]:
fishX = fishData[:,2:5]

In [6]:
fishX

array([[25.4   , 11.52  ,  4.02  ],
       [26.3   , 12.48  ,  4.3056],
       [26.5   , 12.3778,  4.6961],
       [29.    , 12.73  ,  4.4555],
       [29.    , 12.444 ,  5.134 ],
       [29.7   , 13.6024,  4.9274],
       [29.7   , 14.1795,  5.2785],
       [30.    , 12.67  ,  4.69  ],
       [30.    , 14.0049,  4.8438],
       [30.7   , 14.2266,  4.9594],
       [31.    , 14.2628,  5.1042],
       [31.    , 14.3714,  4.8146],
       [31.5   , 13.7592,  4.368 ],
       [32.    , 13.9129,  5.0728],
       [32.    , 14.9544,  5.1708],
       [32.    , 15.438 ,  5.58  ],
       [33.    , 14.8604,  5.2854],
       [33.    , 14.938 ,  5.1975],
       [33.5   , 15.633 ,  5.1338],
       [33.5   , 14.4738,  5.7276],
       [34.    , 15.1285,  5.5695],
       [34.    , 15.9936,  5.3704],
       [34.5   , 15.5227,  5.2801],
       [35.    , 15.4686,  6.1306],
       [35.    , 16.2405,  5.589 ],
       [35.    , 16.36  ,  6.0532],
       [35.    , 16.3618,  6.09  ],
       [36.    , 16.517 ,  5

In [7]:
fishY = fishData[:,1]

In [8]:
fishY

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        450. ,  500. ,  475. ,  500. ,  500. ,  340. ,  600. ,  600. ,
        700. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,  680. ,
        700. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  120. ,  150. ,  145. ,  160. ,  140. ,  160. ,
        169. ,  161. ,  200. ,  180. ,  290. ,  272. ,  390. ,  270. ,
        270. ,  306. ,  540. ,  800. , 1000. ,   55. ,   60. ,   90. ,
        120. ,  150. ,  140. ,  170. ,  145. ,  200. ,  273. ,  300. ,
          5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
      

In [9]:
regFish=sk.linear_model.LinearRegression()
regFish.fit(fishX,fishY)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
regFish.coef_

array([21.42176644, 12.35021761, 44.39709702])

In [11]:
regFish.intercept_

-517.3058304969763

In [13]:
regFish.score(fishX,fishY)

0.881546129383464

In [29]:
fishX2 = fishData[:,2:5]

In [30]:
fishX2

array([[25.4   , 11.52  ,  4.02  ],
       [26.3   , 12.48  ,  4.3056],
       [26.5   , 12.3778,  4.6961],
       [29.    , 12.73  ,  4.4555],
       [29.    , 12.444 ,  5.134 ],
       [29.7   , 13.6024,  4.9274],
       [29.7   , 14.1795,  5.2785],
       [30.    , 12.67  ,  4.69  ],
       [30.    , 14.0049,  4.8438],
       [30.7   , 14.2266,  4.9594],
       [31.    , 14.2628,  5.1042],
       [31.    , 14.3714,  4.8146],
       [31.5   , 13.7592,  4.368 ],
       [32.    , 13.9129,  5.0728],
       [32.    , 14.9544,  5.1708],
       [32.    , 15.438 ,  5.58  ],
       [33.    , 14.8604,  5.2854],
       [33.    , 14.938 ,  5.1975],
       [33.5   , 15.633 ,  5.1338],
       [33.5   , 14.4738,  5.7276],
       [34.    , 15.1285,  5.5695],
       [34.    , 15.9936,  5.3704],
       [34.5   , 15.5227,  5.2801],
       [35.    , 15.4686,  6.1306],
       [35.    , 16.2405,  5.589 ],
       [35.    , 16.36  ,  6.0532],
       [35.    , 16.3618,  6.09  ],
       [36.    , 16.517 ,  5

In [32]:
fishX2 = np.delete(fishX2, 1, axis=1)

In [33]:
fishX2

array([[25.4   ,  4.02  ],
       [26.3   ,  4.3056],
       [26.5   ,  4.6961],
       [29.    ,  4.4555],
       [29.    ,  5.134 ],
       [29.7   ,  4.9274],
       [29.7   ,  5.2785],
       [30.    ,  4.69  ],
       [30.    ,  4.8438],
       [30.7   ,  4.9594],
       [31.    ,  5.1042],
       [31.    ,  4.8146],
       [31.5   ,  4.368 ],
       [32.    ,  5.0728],
       [32.    ,  5.1708],
       [32.    ,  5.58  ],
       [33.    ,  5.2854],
       [33.    ,  5.1975],
       [33.5   ,  5.1338],
       [33.5   ,  5.7276],
       [34.    ,  5.5695],
       [34.    ,  5.3704],
       [34.5   ,  5.2801],
       [35.    ,  6.1306],
       [35.    ,  5.589 ],
       [35.    ,  6.0532],
       [35.    ,  6.09  ],
       [36.    ,  5.8515],
       [36.    ,  6.1984],
       [37.    ,  6.603 ],
       [38.5   ,  6.3063],
       [38.5   ,  6.292 ],
       [39.5   ,  6.7497],
       [41.    ,  6.7473],
       [41.    ,  6.3705],
       [14.1   ,  2.268 ],
       [18.2   ,  2.8217],
 

In [34]:
regFish2=sk.linear_model.LinearRegression()
regFish2.fit(fishX2,fishY)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [36]:
regFish2.coef_

array([20.33385731, 75.33532163])

In [38]:
regFish2.intercept_

-512.2675407788115

In [39]:
regFish2.score(fishX2,fishY)

0.8736774559544478