In [1]:
import numpy as np

In [2]:
### A regular python array

a_py = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
a_py[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
a_py[:-1]

[1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
a_py[0:6:2]

[1, 3, 5]

In [6]:
## Making an numpy array from a regular python arrray
np_ay=np.array(a_py)

In [7]:
np_ay

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
print(np_ay)

[1 2 3 4 5 6 7 8 9]


In [9]:
print(a_py)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [26]:
print(np_ay[::-1])

[9 8 7 6 5 4 3 2 1]


In [13]:
print(a_py[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [14]:
print(np_ay[4::-1])

[5 4 3 2 1]


In [15]:
p=np.array([3,4,5,9,0])

In [16]:
p[:-1]

array([3, 4, 5, 9])

In [22]:
p[:1:-1]

array([0, 9, 5])

In [23]:
ages = np.random.randint(low=30, high=60, size=10)
heights = np.random.randint(low=150, high=210, size=10)

In [24]:
ages

array([37, 34, 57, 54, 48, 58, 52, 42, 43, 39])

In [32]:
heights

array([199, 208, 195, 191, 164, 179, 209, 158, 190, 181])

In [33]:
ages<50

array([ True,  True, False, False,  True, False, False,  True,  True,
        True])

In [35]:
heights[ages<50]

array([199, 208, 164, 158, 190, 181])

In [42]:
np.random.permutation(10)

array([0, 5, 2, 6, 7, 9, 8, 1, 3, 4])

In [44]:
np.argsort(ages)

array([1, 0, 9, 7, 8, 4, 6, 3, 2, 5], dtype=int32)

In [38]:
ages[np.argsort(ages)]

array([34, 37, 39, 42, 43, 48, 52, 54, 57, 58])

In [45]:
a=np.ones(20).reshape(4,5) ## An array of dimension 4 by 5

In [46]:
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
np.shape(a)

(4, 5)

In [48]:
## A function to shuffle a numpy array
def shuffle(p):
    idx=np.random.permutation(len(p))
    return p[idx]

In [49]:
q=np.random.randint(2,30,5)

In [50]:
q

array([14, 12,  7, 13, 25])

In [51]:
np.shape(q)

(5,)

In [52]:
shuffle(q)

array([12, 25, 14,  7, 13])

In [53]:
## np.linspace (a, b, n) gives a numpy array of n equi-spaced points from a to b, including a and b.
a1=np.linspace(0,100,5)

In [54]:
a1

array([  0.,  25.,  50.,  75., 100.])

In [55]:
a1[:4]

array([ 0., 25., 50., 75.])

In [56]:
## np.arange(a, b, n) gives an array of numbers from [a, b) at intervals of length n
a2=np.arange(0,100,30)

In [57]:
a2

array([ 0, 30, 60, 90])

In [58]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [59]:
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [60]:
a[0]

array([1., 2., 3.])

In [61]:
a[1]

array([4., 5., 6.])

In [62]:
a[1,:]

array([4., 5., 6.])

In [63]:
a[1,1]

5.0

In [64]:
a[0,1]

2.0

In [65]:
a[-1]

array([4., 5., 6.])

In [66]:
a[-1,-1]

6.0

In [67]:
a[-1:,-2:]

array([[5., 6.]])

In [69]:
a.shape

(2, 3)

In [70]:
a.dtype

dtype('float64')

In [71]:
len(a)

2

In [72]:
2 in a

True

In [73]:
5 in a

True

In [74]:
7 in a

False

In [75]:
a.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [77]:
a.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])